//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFraemworkLesson2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Windows;

    public partial class Booking_GnidezEntities : DbContext
    {
        public Booking_GnidezEntities()
            : base("name=Booking_GnidezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public void Register(string login, string password)
        {
            //try
            //{
                Users.Add(new User { Login = login, Password = password});
                MessageBox.Show("Added");
                this.SaveChanges();
            //}
            //catch (Exception ex)
            //{
            //    MessageBox.Show(ex.Message);
            //}
        }


        public User GetLogin(string login, string password)
        {
            try
            {
                return Users.Where(e => e.Login == login && e.Password == password).First();
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public virtual DbSet<Rents> Rents { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
