//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFraemworkLesson2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int Id { get; set; }
        public bool IsAvailable { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int UserId { get; set; }
        public int RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
